/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CharacterId = IDL.Text;
export const HomebrewItemId = IDL.Text;
export const CharacterImageKey = IDL.Text;
export const HomebrewArtKey = IDL.Text;
export const UploadResult = IDL.Record({
  'imageKey' : CharacterImageKey,
  'characterId' : CharacterId,
});
export const HomebrewArtResult = IDL.Record({
  'itemId' : HomebrewItemId,
  'artKey' : HomebrewArtKey,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'deleteCharacterImage' : IDL.Func([CharacterId], [], []),
  'deleteHomebrewArt' : IDL.Func([HomebrewItemId], [], []),
  'getCharacterImageKey' : IDL.Func(
      [CharacterId],
      [IDL.Opt(CharacterImageKey)],
      ['query'],
    ),
  'getHomebrewArtKey' : IDL.Func(
      [HomebrewItemId],
      [IDL.Opt(HomebrewArtKey)],
      ['query'],
    ),
  'health' : IDL.Func([], [IDL.Text], ['query']),
  'uploadCharacterImage' : IDL.Func(
      [CharacterId, CharacterImageKey],
      [UploadResult],
      [],
    ),
  'uploadHomebrewArt' : IDL.Func(
      [HomebrewItemId, HomebrewArtKey],
      [HomebrewArtResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CharacterId = IDL.Text;
  const HomebrewItemId = IDL.Text;
  const CharacterImageKey = IDL.Text;
  const HomebrewArtKey = IDL.Text;
  const UploadResult = IDL.Record({
    'imageKey' : CharacterImageKey,
    'characterId' : CharacterId,
  });
  const HomebrewArtResult = IDL.Record({
    'itemId' : HomebrewItemId,
    'artKey' : HomebrewArtKey,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'deleteCharacterImage' : IDL.Func([CharacterId], [], []),
    'deleteHomebrewArt' : IDL.Func([HomebrewItemId], [], []),
    'getCharacterImageKey' : IDL.Func(
        [CharacterId],
        [IDL.Opt(CharacterImageKey)],
        ['query'],
      ),
    'getHomebrewArtKey' : IDL.Func(
        [HomebrewItemId],
        [IDL.Opt(HomebrewArtKey)],
        ['query'],
      ),
    'health' : IDL.Func([], [IDL.Text], ['query']),
    'uploadCharacterImage' : IDL.Func(
        [CharacterId, CharacterImageKey],
        [UploadResult],
        [],
      ),
    'uploadHomebrewArt' : IDL.Func(
        [HomebrewItemId, HomebrewArtKey],
        [HomebrewArtResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };